### PR TITLE
Final task by rohan

### PR DESCRIPTION
**Pull request by Rohan69420**
Merge conflict and resolution

### CODE REVIEW

**Review by avisekksarma — CHANGES_REQUESTED** [review]
rohan bhai, timro full name and campus name lekhera naya pull request pathau hai 
- Context: point 2 of contributing.md file ko kura

**Comment by Rohan69420** [comment]
updated

**Review by avisekksarma — COMMENTED** [review]
okay great

**Comment by avisekksarma** [comment]
stories directory ko name "Stories" raixa timro , so feri milauna parni vayo maile
okay ma garxu

**Pull request merged**
