### PR TITLE
Whoisdinanath

### PR DESCRIPTION
**Pull request by whoisdinanath**
First I created a new branch of my username, then did all the assignments in that branch and pushed the branch to my repo. Then i am creating a pull request for it.

### CODE REVIEW

**Review by avisekksarma — CHANGES_REQUESTED** [review]
There are couple of changes you need to do:
1. delete the files "tha078bei010.txt" and "whoisdinanath.txt" outside of stories folder
2. rename the stories folder to "stories" ( smallcase 's' )

**Comment by avisekksarma** [comment]
Then submit a new pull request

**Comment by whoisdinanath** [comment]
made the changes

**Comment by avisekksarma** [comment]
Yeah, thats great now

**Pull request merged**
